### ISSUE TITLE
Installation issue- drupal 8.8.5

### ISSUE THREAD

**Issue by dhruva7** [creativepropulsionlabs/commerce_rma#1]
Hi I was trying to install the module, it was showing the following issue while trying to install. 

Also the below rma workflow is not showing. Where I can add the workflow for the  Commerce return item type entities

![image](https://user-images.githubusercontent.com/18899830/86468842-dfa19580-bd55-11ea-836e-612fffcb6ba2.png)

```
Error: Call to a member function getConfigDependencyName() on null in Drupal\Core\Entity\EntityDisplayBase->calculateDependencies() (line 325 of /home/dhruva/webapps/list/core/lib/Drupal/Core/Entity/EntityDisplayBase.php)
#0 /home/dhruva/webapps/list/core/modules/layout_builder/src/Entity/LayoutBuilderEntityViewDisplay.php(384): Drupal\Core\Entity\EntityDisplayBase->calculateDependencies()
```

Thanks and regards

**Comment by dhruva7** [comment]
There is another problem while going for the return request is:-

RuntimeException: The "customer_profile" plugin requires the "profile_scope" configuration key in Drupal\commerce\Plugin\Commerce\InlineForm\InlineFormBase->validateConfiguration() (line 89 of /home/dhruva/webapps/ecommerce/modules/contrib/commerce/src/Plugin/Commerce/InlineForm/InlineFormBase.php).

**Comment by Danishkhurshid** [comment]
You can fix the installation problem by applying this patch on the core https://www.drupal.org/files/issues/2019-11-04/3062441-5.patch

**Comment by Danishkhurshid** [comment]
@dhruva7 For this issue i have raised a pull request.

**Comment by dhruva7** [comment]
@Danishkhurshid thanks for the help dude, I have seen your pull request, is it solved. As I am also having the similar issue related to the return tab. The issue is with profile scope.
`RuntimeException: The "customer_profile" plugin requires the "profile_scope" configuration key in Drupal\commerce\Plugin\Commerce\InlineForm\InlineFormBase->validateConfiguration() (line 89 of /home/dhruva/webapps/iunoa/modules/contrib/commerce/src/Plugin/Commerce/InlineForm/InlineFormBase.php).`

**Comment by Danishkhurshid** [comment]
@dhruva7 Yep. Since the PR hasn't been merged yet you can apply the pull request changes as a patch and It will work.

**Comment by dhruva7** [comment]
Hi @Danishkhurshid , is your pull request working for drupal 8.9? or on your website as I am still getting the same error.

**Comment by Danishkhurshid** [comment]
@dhruva7 Try applying the pull request as patch. It is working for me.

**Comment by dhruva7** [comment]
@Danishkhurshid bro, how did you manage the commerce return type entities missing workflow issue as I have uploaded in the screenshot? 

> 
> 
> Hi I was trying to install the module, it was showing the following issue while trying to install.
> 
> Also the below rma workflow is not showing. Where I can add the workflow for the Commerce return item type entities
> 
> ![image](https://user-images.githubusercontent.com/18899830/86468842-dfa19580-bd55-11ea-836e-612fffcb6ba2.png)
> 
> ```
> Error: Call to a member function getConfigDependencyName() on null in Drupal\Core\Entity\EntityDisplayBase->calculateDependencies() (line 325 of /home/dhruva/webapps/list/core/lib/Drupal/Core/Entity/EntityDisplayBase.php)
> #0 /home/dhruva/webapps/list/core/modules/layout_builder/src/Entity/LayoutBuilderEntityViewDisplay.php(384): Drupal\Core\Entity\EntityDisplayBase->calculateDependencies()
> ```
> 
> Thanks and regards

**Comment by Danishkhurshid** [comment]
@dhruva7 oh! Actually we didn't require setting up the workflow for item entities. Our use case was pretty simple and we only have one order item type to work with. :) I will do some debugging around this.

**Comment by dhruva7** [comment]
Thanks mate, also, there is another bug while accepting the return request- RuntimeException: The "customer_profile" plugin requires the "profile_scope" configuration key in Drupal\commerce\Plugin\Commerce\InlineForm\InlineFormBase->validateConfiguration() (line 89 of /home/dhruva/webapps/iuooa/modules/contrib/commerce/src/Plugin/Commerce/InlineForm/InlineFormBase.php).

You are right, I think this module is perfect while need not to add any further edits.

**Comment by dhruva7** [comment]
I think both the workflow is required. As in return page a customer have two options -1- Return Reason 2- Expected resolution. 
If he selects only return reason than it will reload the same page and will happen nothing. In case we have added the expected resolution such as refund needed or exchange required than it shows the following errors.

`Error: Call to a member function getEntity() on null in Drupal\commerce_rma\Plugin\views\field\CommerceReturnEditQuantity->viewsFormSubmit() (line 354 of /home/dhruva/webapps/iunoa/modules/commerce_rma-8.x-1.x/src/Plugin/views/field/CommerceReturnEditQuantity.php) `

`Notice: Undefined index: shipping_profile in Drupal\commerce_rma\Plugin\views\field\CommerceReturnEditQuantity->viewsFormSubmit() (line 352 of /home/dhruva/webapps/iunoa/modules/commerce_rma-8.x-1.x/src/Plugin/views/field/CommerceReturnEditQuantity.php)`
